### ISSUE TITLE
Cannot start migration

### ISSUE THREAD

**Issue by cmcau** [tableau/tableau-migration-sdk#11]
I need some help with running a migration.  I only want to test migrating projects at the moment, I know I haven't specified a manifest, but I can't find where/how to do that in the documentation.

The output when I run the script is:

> 2024-03-01 14:23:49,158 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - Start processing HTTP request GET https://REDACTED_SERVER.com.au/api/2.4/serverinfo
> 2024-03-01 14:23:49,260 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Sending HTTP request GET https://REDACTED_SERVER.com.au/api/2.4/serverinfo
> 2024-03-01 14:23:49,296 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - Start processing HTTP request GET https://prod-apsoutheast-a.online.tableau.com/api/2.4/serverinfo
> 2024-03-01 14:23:49,296 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Sending HTTP request GET https://prod-apsoutheast-a.online.tableau.com/api/2.4/serverinfo
> 2024-03-01 14:23:49,981 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Received HTTP response headers after 716.0052ms - 200
> 2024-03-01 14:23:50,015 - Tableau.Migration.Net.NetworkTraceLogger - INFO - HTTP GET https://login.microsoftonline.com/9c4a6e52-9234-4976-a921-ff37596a2a0a/oauth2/authorize?response_type=code&client_id=d6c527c4-7bf3-46f2-81df-e42269eb870b&scope=openid&nonce=02ed78d3-ce80-4f9e-bcda-280355588ce6&redirect_uri=https%3a%2f%2fREDACTED_SERVER.com.au%2f&state=AppProxyState%3a{"InvalidTokenRetry"%3anull%2c"IsMsofba"%3afalse%2c"OriginalRawUrl"%3a"https%3a%5c%2f%5c%2fREDACTED_SERVER.com.au%5c%2fapi%5c%2f2.4%5c%2fserverinfo"%2c"RequestProfileId"%3anull%2c"SessionId"%3a"5f5ef37e-1d46-4183-858d-70b373122606"}%23EndOfStateParam%23&client-request-id=5f5ef37e-1d46-4183-858d-70b373122606&claims={"id_token"%3a{"xms_cc"%3a{"values"%3a%5b"CP1"%5d}}} responded OK. Details: 
> 2024-03-01 14:23:50,019 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '817.7996'
> 2024-03-01 14:23:50,021 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '822.277'
> 2024-03-01 14:23:50,024 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - End processing HTTP request after 886.8879ms - 200
> 2024-03-01 14:23:50,964 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Received HTTP response headers after 1666.2483ms - 200
> 2024-03-01 14:23:50,965 - Tableau.Migration.Net.NetworkTraceLogger - INFO - HTTP GET https://prod-apsoutheast-a.online.tableau.com/api/2.4/serverinfo responded OK. Details: 
> 2024-03-01 14:23:50,966 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '1669.2406'
> 2024-03-01 14:23:50,967 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '1669.8717'
> 2024-03-01 14:23:50,967 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - End processing HTTP request after 1671.0498ms - 200
> 2024-03-01 14:23:51,077 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - Start processing HTTP request POST https://prod-apsoutheast-a.online.tableau.com/api/3.22/auth/signin
> 2024-03-01 14:23:51,077 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Sending HTTP request POST https://prod-apsoutheast-a.online.tableau.com/api/3.22/auth/signin
> 2024-03-01 14:23:52,774 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Received HTTP response headers after 1696.3423ms - 200
> 2024-03-01 14:23:52,774 - Tableau.Migration.Net.NetworkTraceLogger - INFO - HTTP POST https://prod-apsoutheast-a.online.tableau.com/api/3.22/auth/signin responded OK. Details: 
> 2024-03-01 14:23:52,775 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '1698.1129'
> 2024-03-01 14:23:52,775 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '1698.3837'
> 2024-03-01 14:23:52,775 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - End processing HTTP request after 1699.0799ms - 200
> 2024-03-01 14:23:52,936 - Tableau.Migration.Engine.Manifest.MigrationManifest - ERROR - An error occurred during migration. Error: System.NotSupportedException: Content Type text/html not supported
>    at Tableau.Migration.Net.HttpContentSerializer.DeserializeAsync[T](HttpContent content, CancellationToken cancel)
>    at Tableau.Migration.Net.DefaultHttpClient.CreateDeserializedResponseAsync[TResponse](Task`1 getResponse, CancellationToken cancellationToken)
>    at Tableau.Migration.Net.DefaultHttpClient.SendAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
>    at Tableau.Migration.Net.HttpRequestBuilder`2.SendAsync[TResponse](CancellationToken cancellationToken)
>    at Tableau.Migration.Api.IHttpResponseMessageExtensions.ToResultAsync[TResponse,TModel](Task`1 getResponseAsync, Func`2 createModel, ISharedResourcesLocalizer sharedResourcesLocalizer)
> 2024-03-01 14:23:52,937 - Tableau.Migration.Engine.Migrators.Migrator - ERROR - One or more endpoints could not be initialized. Migration cannot start.
> All done
> 
> Process finished with exit code 0
> 

Please let me know what is wrong or point me in the direction of what I've missed.

**Comment by rbanderton** [comment]
At first glance it appears there's a redirect from your source server to an interactive Microsoft login. Is there a maybe a proxy involved?

**Comment by cmcau** [comment]
hmmm ... possibly.  Both Server and Cloud are SSO via Microsoft, but I thought the PAT meant that you wouldn't need to authenticate via SSO at all.

**Comment by rbanderton** [comment]
Use of PAT indeed doesn't need to authenticate with SSO, but the network trace above shows that the Microsoft login happens before we even get to API authentication (the "OriginalRawUrl" is for a [server info](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_server.htm#server_info) call). It seems to be a proxy enforcing SSO authentication on all requests, even to `/api` paths.

**Comment by rbanderton** [comment]
Closing due to inactivity.
