### ISSUE TITLE
"Value cannot be null" error when running migration

### ISSUE THREAD

**Issue by cmcau** [tableau/tableau-migration-sdk#14]
Sorry, me again, I've made more progress but still getting caught with errors.

`
2024-04-13 11:33:01,749 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - Start processing HTTP request GET https://SERVER_URL_REDACTED/api/3.15/sites/0a47b501-df72-464a-a651-8f971cf8172d/users?pageSize=100&pageNumber=1
2024-04-13 11:33:01,750 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Sending HTTP request GET https://SERVER_URL_REDACTED/api/3.15/sites/0a47b501-df72-464a-a651-8f971cf8172d/users?pageSize=100&pageNumber=1
2024-04-13 11:33:01,838 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Received HTTP response headers after 86.9128ms - 200
2024-04-13 11:33:01,838 - Tableau.Migration.Net.NetworkTraceLogger - INFO - HTTP GET https://SERVER_URL_REDACTED/api/3.15/sites/0a47b501-df72-464a-a651-8f971cf8172d/users?pageSize=100&pageNumber=1 responded OK. Details: 
2024-04-13 11:33:01,838 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '88.285'
2024-04-13 11:33:01,838 - Polly - INFO - Execution attempt. Source: 'DefaultHttpClient-TableauMigrationSDK//Retry', Operation Key: '', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '88.49'
2024-04-13 11:33:01,839 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - End processing HTTP request after 89.6576ms - 200
2024-04-13 11:33:01,878 - Tableau.Migration.Engine.Manifest.MigrationManifest - ERROR - An error occurred during migration. Error: System.ArgumentNullException: Value cannot be null. (Parameter 'response.Domain')
   at Tableau.Migration.Guard.AgainstNull[T](T value, String paramName)
   at Tableau.Migration.Guard.AgainstNull[T](T value, Expression`1 expression)
   at Tableau.Migration.Content.User..ctor(UserType response)
   at Tableau.Migration.Api.UsersResponseExtensions.<>c.<GetUsersFromResponse>b__0_0(UserType u)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Tableau.Migration.Api.UsersResponseExtensions.GetUsersFromResponse(UsersResponse response)
   at Tableau.Migration.Api.UsersApiClient.<>c.<GetAllUsersAsync>b__4_0(UsersResponse r)
   at Tableau.Migration.Api.IHttpResponseMessageExtensions.ToPagedResult[TResponse,TModel](IHttpResponseMessage`1 response, Func`2 createModel, ISharedResourcesLocalizer sharedResourcesLocalizer)
2024-04-13 11:33:01,881 - System.Net.Http.HttpClient.DefaultHttpClient.LogicalHandler - INFO - Start processing HTTP request POST https://SERVER_URL_REDACTED/api/3.15/auth/signout
2024-04-13 11:33:01,882 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Sending HTTP request POST https://SERVER_URL_REDACTED/api/3.15/auth/signout
2024-04-13 11:33:01,933 - System.Net.Http.HttpClient.DefaultHttpClient.ClientHandler - INFO - Received HTTP response headers after 51.2618ms - 204
`

There's 433 users on the Server.
I am NOT an Admin on Tableau Cloud (and I don't think we have that many licenses anyway), but am I even to the stage of creating users on Tableau Cloud ?

**Comment by cmcau** [comment]
OK, so now I am the Site Admin on Tableau CLoud and I'm still getting the same error.  
Is there a way to help prioritise this?  I'm getting closer to a deadline and still getting errors when running the script.

**Comment by cmcau** [comment]
Tableau Server and Tableau Cloud are configured for SSO

**Comment by cmcau** [comment]
If I run in simulator mode, I get these errors:

Detail: Tables in projects feature is disabled.
Detail: Databases in projects feature is disabled.

**Comment by rbanderton** [comment]
What version of Tableau Server is being used? The API version above appears to be for 2022.1, which I'll note just went out of support. If that's the case you'll want to upgrade regardless of this issue.

**Comment by cmcau** [comment]
Thanks for the reply, but I don't think that's a viable option for the client.  Yes, their Server is 2022.1.3 (20221.22.0616.1738) 64-bit Windows

I'll confirm with them, but I don't think they want to upgrade a production Server for the only reason to migrate to Cloud.

**Comment by rbanderton** [comment]
Obviously their call, but to be clear v2022.1 is outside of the [Tableau Server support window](https://www.tableau.com/support/services#supported-versions), so this isn't just for Migration SDK. They won't be able to get support on general issues for that version, either.
