### ISSUE TITLE
Under simulation, all attempted workbook migrations fail

### ISSUE THREAD

**Issue by jdub** [tableau/tableau-migration-sdk#19]
Using 3.0.1, currently under simulation because I haven't yet figured out how to [serialise/deserialise a manifest](https://github.com/tableau/tableau-migration-sdk/issues/18).

I have filtered the workbooks such that all but 10 are skipped. This is the first time I've been able to get the simulation to complete.

However, all 10 fail:

```
        IWorkbook
        	0/887 succeeded
        	877/887 skipped
        	10/887 errored
        	0/887 cancelled
        	0/887 pending
```

7 workbooks fail with this error:

```
2024-05-19 23:23:35,631 - Tableau.Migration.Engine.Manifest.MigrationManifestContentTypePartition - ERROR - An error occurred migrating Tableau.Migration.Content.IWorkbook item "<REDACTED>". Error: Tableau.Migration.Api.Rest.RestException: An error was returned from the Tableau API:
URL:
Code: 400008
Summary: Unable to parse file
Detail:
   at Tableau.Migration.Api.IHttpResponseMessageExtensions.ToResultAsync[TResponse,TModel](IHttpResponseMessage`1 response, Func`3 createModelAsync, ISharedResourcesLocalizer sharedResourcesLocalizer, CancellationToken cancel)
```

3 workbooks fail with this error:

```
2024-05-19 23:24:48,700 - Tableau.Migration.Engine.Manifest.MigrationManifestContentTypePartition - ERROR - An error occurred migrating Tableau.Migration.Content.IWorkbook item "<REDACTED>". Error: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Linq.Enumerable.ConcatNIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.ConcatNIterator`1.PreallocatingToArray()
   at System.Linq.Enumerable.ConcatNIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tableau.Migration.Api.Simulation.Rest.Net.Responses.RestCommitUploadResponseBuilder`3.BuildResponseAsync(HttpRequestMessage request, CancellationToken cancel)
   at Tableau.Migration.Api.Simulation.Rest.Net.Responses.RestApiResponseBuilderBase`1.RespondAsync(HttpRequestMessage request, CancellationToken cancel)
   at Tableau.Migration.Api.Simulation.TableauApiResponseSimulator.RespondAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Tableau.Migration.Net.Simulation.SimulationHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Tableau.Migration.Net.Handlers.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Tableau.Migration.Net.Handlers.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Tableau.Migration.Net.Handlers.AuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Resilience.ResilienceHandler.<>c.<<SendAsync>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Http.Resilience.ResilienceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Tableau.Migration.Net.DefaultHttpClient.CreateDeserializedResponseAsync[TResponse](Task`1 getResponse, CancellationToken cancellationToken)
   at Tableau.Migration.Net.DefaultHttpClient.SendAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
   at Tableau.Migration.Net.HttpRequestBuilder`2.SendAsync[TResponse](CancellationToken cancellationToken)
   at Tableau.Migration.Api.IHttpResponseMessageExtensions.ToResultAsync[TResponse,TModel](Task`1 getResponseAsync, Func`3 createModelAsync, ISharedResourcesLocalizer sharedResourcesLocalizer, CancellationToken cancel)
```

**Comment by dngtableau** [comment]
For the 7 workbooks that failed, that's Tableau Server responding it was unable to parse the workbook. Can you provide the Tableau Server version for your source and destination server you're using? My guess is there's a version incompatibility between the source and destination.

The second error looks like an exception thrown by the SDK. I'll file a defect on our end to continue the investigation.

**Comment by drache42** [comment]
Due to inactivity, this issue will be closed. Feel free to reopen or create a new one if needed.
