### ISSUE TITLE
load_manifest() in Python not serializing properly

### ISSUE THREAD

**Issue by jyoung-slalom** [tableau/tableau-migration-sdk#27]
When executing a migration using tableau_migration 4.1.0 and using the testcomponents libraries to handle JSON manifests, the Python module is not properly importing/serializing the data from the JSON files.  In my example use-case, the following steps were followed:

1. Mapping functions were created to re-organize the project structure when migrating content to Tableau Cloud.
2. Tests were run skipping all content to validate the mapping functions via the manifest.
3. Projects were migrated using the mapping functions, and a manifest was created.
4. The manifest was then loaded to migrate data sources.
5. The manifest created by the new migration plan run cleared the stored variables of the project destinations, resetting all project destination key-value lists to null. (Mapping details remained in-tact).
6. During the migration run to migrate data sources, the data sources would download but then fail to upload as the destination was null. (Error pasted below).

I attempted several fixes, including running with/without mapping for data sources, with/without mapping for projects during data source migration, with the same net result.

```
2024-07-08 18:41:19,629|ERROR|Tableau.Migration.Engine.Manifest.MigrationManifestContentTypePartition|An error occurred migrating Tableau.Migration.Content.IDataSource item "Data Sources/Datasource: XXX/Datasource Name". Error: System.ArgumentNullException: Value cannot be null. (Parameter 'value')

   at Tableau.Migration.Guard.AgainstNull[T](T value, String paramName)

   at Tableau.Migration.Content.ContainerContentBase.set_MappableContainer(IContentReference value)

   at Tableau.Migration.Content.MappableContainerContentBase.Tableau.Migration.Content.IMappableContainerContent.SetLocation(IContentReference container, ContentLocation newLocation)

   at Tableau.Migration.Engine.Preparation.ContentItemPreparerBase`2.ApplyMappingAsync(TPublish publishItem, ContentLocation mappedLocation, CancellationToken cancel)

   at Tableau.Migration.Engine.Preparation.ContentItemPreparerBase`2.PreparePublishItemAsync(ContentMigrationItem`1 item, TPublish publishItem, CancellationToken cancel)

   at Tableau.Migration.Engine.Preparation.ContentItemPreparerBase`2.PreparePublishItemAsync(ContentMigrationItem`1 item, TPublish publishItem, CancellationToken cancel)
```

**Comment by drache42** [comment]
The TestComponents library is not a supported by migration-sdk and should only be used at your own risk. It's our internal code to help us with testing.

However, the serializer will soon be moved from the TestComponents (which will be removed) to the main library. When this happens, please refactor your code and try again.
**Note**: This will not be marked as breaking change, as the de/serializer was never supported to begin with.
