### ISSUE TITLE
Error while requesting workbooks API

### ISSUE THREAD

**Issue by samuelTyh** [tableau/tableau-migration-sdk#36]
**Python version: 3.12.4
tableau_migration: 4.3.0**

Hello peep, I encountered an issue while running a test migration with Python SDK. The context is I only moved a small group of users, 1 user group and a top-level project with permission granted to the user group. Migration with filters work fine for users, groups and datasources, but workbooks' migration can't proceed as expected.

I checked the log and see the following C sharp error code and it's source code, and seems like the request for workbook list to API didn't work out because the owner can't be found? Is it because I didn't run the migration for all users, or is there something I overlooked? 

Not sure if any of you have the same issue, would be great if someone could shed a light for me, thanks!

```
Tableau.Migration.Engine.Manifest.MigrationManifest - ERROR - An error occurred during migration. Error: System.ArgumentNullException: Value cannot be null.
   at Tableau.Migration.Guard.AgainstNull[T](T value, String paramName)
   at Tableau.Migration.Api.IContentReferenceFinderFactoryExtensions.<>c__2`1.<FindOwnerAsync>b__2_0(T r)
   at Tableau.Migration.Api.IContentReferenceFinderFactoryExtensions.FindAsync[TResponse,TContent](IContentReferenceFinderFactory finderFactory, TResponse response, Func`2 getResponseId, ILogger logger, ISharedResourcesLocalizer localizer, Boolean throwIfNotFound, String warningMessageResource, String exceptionMessageResource, CancellationToken cancel)
   at Tableau.Migration.Api.IContentReferenceFinderFactoryExtensions.FindOwnerAsync[T](IContentReferenceFinderFactory finderFactory, T response, ILogger logger, ISharedResourcesLocalizer localizer, Boolean throwIfNotFound, CancellationToken cancel)
   at Tableau.Migration.Api.ContentApiClientBase.FindOwnerAsync[T](T response, Boolean throwIfNotFound, CancellationToken cancel)
   at Tableau.Migration.Api.WorkbooksApiClient.<GetAllWorkbooksAsync>b__14_0(WorkbooksResponse r, CancellationToken c)
   at Tableau.Migration.Api.IHttpResponseMessageExtensions.ToPagedResultAsync[TResponse,TModel](IHttpResponseMessage`1 response, Func`3 createModelAsync, ISharedResourcesLocalizer sharedResourcesLocalizer, CancellationToken cancel)

**Comment by drache42** [comment]
Hi @samuelTyh,
I can't be 100% sure from just that one log message alone, but your theory is very plausible.

If you filter out users, and then migrate workbooks that are owned by that user, you'll see an error. That is because the sdk will try to reassign the original user on the destination side. If you filter that user out, clearly that won't work as that user is not on the destination.

Whenever you filter users, you should also create a mapping for those users to remap them to a known user. 

We do the same thing in the example app.
We have a [Unlicensed User Filter](https://github.com/tableau/tableau-migration-sdk/blob/main/examples/Csharp.ExampleApplication/Hooks/Filters/UnlicensedUsersFilter.cs#L21) which filters all users that are unlicensed on the source.
and then we have a [Unlicensed User Mapping](https://github.com/tableau/tableau-migration-sdk/blob/main/examples/Csharp.ExampleApplication/Hooks/Mappings/UnlicensedUsersMapping.cs#L38) to map those users to a different user that is known to exist on the destination.
